# Generated by Django 5.1.1 on 2024-09-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relevancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='static/biblioteca/images/relevancia/')),
            ],
        ),
        migrations.CreateModel(
            name='Sexualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=255)),
                ('ano_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.ano')),
                ('palavras_chave', models.ManyToManyField(related_name='artigos', to='biblioteca.palavrachave')),
                ('relevancia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.relevancia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('nascimento', models.DateField()),
                ('senha', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('data_registro', models.DateField()),
                ('instituicao', models.CharField(default='Escola', max_length=100)),
                ('foto', models.ImageField(default='static/biblioteca/images/perfil/foto_perfil.png', upload_to='static/biblioteca/images/perfil/')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero')),
                ('sexualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.sexualidade')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.vinculo')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favorito', models.DateField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.artigo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='usuario',
            field=models.ManyToManyField(related_name='artigos', to='biblioteca.usuarios'),
        ),
    ]
