# Generated by Django 5.1.1 on 2024-09-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevancia',
            name='imagem',
            field=models.ImageField(upload_to='biblioteca/images/relevancia/'),
        ),
    ]
