# Generated by Django 5.1.1 on 2025-01-15 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_relevancia_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='usuario',
            field=models.ManyToManyField(related_name='artigos', to=settings.AUTH_USER_MODEL),
        ),
    ]
