# Generated by Django 5.1.1 on 2025-02-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_submissao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submissao',
        ),
    ]
